name: Build iOS IPA with Agora

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: echo "workflow ok"
